export const equipmentList = [
  {
    name: 'Sword',
    damage: 'Melee + 1d6',
    durability: 'n/a',
    useCost: 8,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Pistol',
    damage: '2d6',
    durability: 'n/a',
    useCost: 5,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 8,
    range: '30ft - 60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Rifle',
    damage: '2d8',
    durability: 'n/a',
    useCost: 5,
    sellValue: 3000,
    buyValue: 6000,
    ammo: 6,
    range: '30ft - 120ft',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Hammer',
    damage: 'Melee + 1d8',
    durability: 'n/a',
    useCost: 10,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Shield',
    damage: 'Melee',
    durability: 20,
    useCost: 5,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Block an attack and take no damage. But lose durability',
  },
  {
    name: 'Axe',
    damage: 'Melee + 1d8',
    durability: 'n/a',
    useCost: 10,
    sellValue: 3000,
    buyValue: 6000,
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Spear',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 8,
    sellValue: 2000,
    buyValue: 4000,
    ammo: 'n/a',
    range: 'Melee range + 5',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Trident',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 8,
    sellValue: 3000,
    buyValue: 6000,
    ammo: 'n/a',
    range: 'Melee range + 5',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Knife',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 6,
    sellValue: 1000,
    buyValue: 2000,
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Shigure',
    damage: 'Melee + 1d8',
    durability: 'n/a',
    useCost: 8,
    sellValue: 'n/a',
    buyValue: 'n/a',
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Chains',
    damage: 'Melee + 1d6',
    durability: 'n/a',
    useCost: 8,
    sellValue: 1500,
    buyValue: 3000,
    ammo: 'n/a',
    range: 'Melee range + 10',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Knuckles',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 5,
    sellValue: 1000,
    buyValue: 2000,
    ammo: 'n/a',
    range: 'Melee Range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'sythe',
    damage: 'Melee + 1d6',
    durability: 'n/a',
    useCost: 8,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'Melee range + 5',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Cross Bow',
    damage: '2d4',
    durability: 'n/a',
    useCost: 5,
    sellValue: 2000,
    buyValue: 4000,
    ammo: 'n/a',
    range: '30ft - 60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'flame arrow',
    damage: '3d4',
    durability: 'n/a',
    useCost: 0,
    sellValue: 250,
    buyValue: 500,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Sea Prism Tip Shield',
    damage: 'Melee',
    durability: 60,
    useCost: 5,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: 'Melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Has a sea prism tip',
  },
  {
    name: 'Long Neck Rifle',
    damage: '2d8',
    durability: 'n/a',
    useCost: 5,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 6,
    range: '30ft - 240ft',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Pistol+MagAttach',
    damage: '2d6',
    durability: 'n/a',
    useCost: 5,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 10,
    range: '30ft-60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Hand Grenade',
    damage: '3d4',
    durability: 'n/a',
    useCost: 5,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: '60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Flare',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 5,
    sellValue: 1500,
    buyValue: 3000,
    ammo: 'n/a',
    range: '60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Used for lighting up an area. Even underwater',
  },
  {
    name: 'Lighter',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 5,
    sellValue: 1250,
    buyValue: 2500,
    ammo: 'n/a',
    range: 'Melee Range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'You can start fires very easy. No need to roll for it',
  },
  {
    name: 'BlastPouch',
    damage: '2d8',
    durability: 'n/a',
    useCost: 5,
    sellValue: 1500,
    buyValue: 3000,
    ammo: 'n/a',
    range: 'Melee Range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Single Use, Stick to weapon or body, detonates on contact',
  },
  {
    name: 'Disposable Cannon Launcher',
    damage: '3d10',
    durability: 1,
    useCost: 10,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 1,
    range: '30ft - 60ft',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Disposable Cannon launcher. 1 time use',
  },
  {
    name: 'CannonBall',
    damage: '3d8',
    durability: 'n/a',
    useCost: 0,
    sellValue: 10000,
    buyValue: 20000,
    ammo: 'n/a',
    range: '60ft - 120ft',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: '3d8 direct hit. 1d8 in blast radius',
  },
  {
    name: 'Medical Tools',
    damage: 'n/a',
    durability: 5,
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Required Tools for Making Quality Medicine',
  },
  {
    name: 'Fishing Rod',
    damage: 'n/a',
    durability: 20,
    useCost: 4,
    sellValue: 750,
    buyValue: 1500,
    ammo: 'n/a',
    range: '30ft - 60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Used for fishing',
  },
  {
    name: 'Iron Fishing Rod',
    damage: 'n/a',
    durability: 40,
    useCost: 4,
    sellValue: 2000,
    buyValue: 4000,
    ammo: 'n/a',
    range: '30ft - 60ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Used for fishing + 20 durability',
  },
  {
    name: 'Ball Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: '30ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Creates a ball of cloud. Used for floating platforms',
  },
  {
    name: 'Breath Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 3000,
    buyValue: 6000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Propels things +30ft',
  },
  {
    name: 'Flame Dial',
    damage: '2d6',
    durability: 'n/a',
    useCost: 0,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: '30ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'A range of 30ft long and 10ft across fire damage',
  },
  {
    name: 'Flash Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 3000,
    buyValue: 6000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'A bright flash that stuns enemies in a 30ft range for 1 turn',
  },
  {
    name: 'Impact Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: '5ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Block attack with this. Absorbs all damage. Release energy take all dmg',
  },
  {
    name: 'Lamp Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 1000,
    buyValue: 2000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Creates a steady light in a 60ft radius for 10 minutes',
  },
  {
    name: 'Reject Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 7500,
    buyValue: 15000,
    ammo: 'n/a',
    range: '5ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'The same as Impact. Though amplifies by 10',
  },
  {
    name: 'Water Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 1000,
    buyValue: 2000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Holds water and releases it. Holds up to 10ft by 10ft',
  },
  {
    name: 'Explosive Barrel',
    damage: '4d10',
    durability: 1,
    useCost: 0,
    sellValue: 10000,
    buyValue: 20000,
    ammo: 'n/a',
    range: '30ft',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Ship Repairs',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 25000,
    buyValue: 50000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'heavy',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'One time use. Heals a player and stops bleeding roll 2d6',
  },
  {
    name: 'Medic Kit',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'make balls of iron that weigh the same as clouds. You can shape it',
  },
  {
    name: 'Iron Dial',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 25000,
    buyValue: 50000,
    ammo: 'n/a',
    range: '30ft',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Holds a 5ft cube of water',
  },
  {
    name: 'Fluid Pouch',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 1250,
    buyValue: 2500,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Okay Small fish',
    damage: 'Melee',
    durability: 'n/a',
    useCost: 0,
    sellValue: 100,
    buyValue: 200,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Good Small fish',
    damage: 'Melee',
    durability: 'n/a',
    useCost: 0,
    sellValue: 175,
    buyValue: 350,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Excellent Small fish',
    damage: 'Melee',
    durability: 'n/a',
    useCost: 0,
    sellValue: 250,
    buyValue: 500,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Okay Medium fish',
    damage: 'Melee',
    durability: 'n/a',
    useCost: 0,
    sellValue: 200,
    buyValue: 400,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Good Medium fish',
    damage: 'Melee',
    durability: 'n/a',
    useCost: 0,
    sellValue: 225,
    buyValue: 450,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Excellent Medium fish',
    damage: 'Melee',
    durability: 'n/a',
    useCost: 0,
    sellValue: 250,
    buyValue: 500,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Okay Large fish',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 0,
    sellValue: 300,
    buyValue: 600,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Good Large fish',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 0,
    sellValue: 350,
    buyValue: 700,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Excellent Large fish',
    damage: 'Melee + 1d4',
    durability: 'n/a',
    useCost: 0,
    sellValue: 400,
    buyValue: 800,
    ammo: 'n/a',
    range: 'melee range',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'n/a',
  },
  {
    name: 'Small bottle',
    damage: 'n/a',
    durability: 2,
    useCost: 0,
    sellValue: 250,
    buyValue: 500,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Good for 2 to 3 people',
  },
  {
    name: 'Large bottle',
    damage: 'n/a',
    durability: 4,
    useCost: 0,
    sellValue: 500,
    buyValue: 1000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Good for 4 to 5 people',
  },
  {
    name: 'High quality',
    damage: 'n/a',
    durability: 6,
    useCost: 0,
    sellValue: 1500,
    buyValue: 3000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Good for 4 to 6 people',
  },
  {
    name: 'Distilling Tools',
    damage: 'n/a',
    durability: 5,
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Required tools for distilling alcohol 5 uses',
  },
  {
    name: 'HQ Distill Tools',
    damage: 'n/a',
    durability: 5,
    useCost: 0,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Required tools for distilling alcohol 5 uses',
  },
  {
    name: 'GlassWare',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 1250,
    buyValue: 2500,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'light',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Used For distilling and making chemicals',
  },
  {
    name: 'Low quality Base Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 500,
    buyValue: 1000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '10 days',
    yield: '1 Bud',
    description: 'Mix a seed with a bud of another seed to grow more of that seed',
  },
  {
    name: 'Mid Quality Base Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 1500,
    buyValue: 3000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '9 days',
    yield: '1 to 2 Buds',
    description: 'Mix a seed with a bud of another seed to grow more of that seed',
  },
  {
    name: 'High Quality Base Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '8 days',
    yield: '2 to 3 Buds',
    description: 'Mix a seed with a bud of another seed to grow more of that seed',
  },
  {
    name: 'Stick Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'Smoke the bud, mix into a drink. Makes you sticky',
  },
  {
    name: 'Bounce Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'Makes you bouncy - You dont stop bouncing Reflex +1 Range Hit DC +1',
  },
  {
    name: 'Absorb Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'Pant next to 2 different buds. Creates a new plant with 1 or both effects.',
  },
  {
    name: 'Joy Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'You become happy - Unaffected by negative mental states',
  },
  {
    name: 'Rage Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 4000,
    buyValue: 8000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'You rage - Strength + 2',
  },
  {
    name: 'Copy Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 to 2 Buds',
    description: 'Plant this seed next to any plant. Makes an off brand copy of that plant.',
  },
  {
    name: 'Clairvoyance Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'You can a roll 1d4 to roll for checks',
  },
  {
    name: 'Resistance Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'You can roll 1d4 to roll for saves',
  },
  {
    name: 'Famine Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'You dont need to eat. Resets on long rest',
  },
  {
    name: 'Plus Minus Seed',
    damage: 'n/a',
    durability: 'n/a',
    useCost: 0,
    sellValue: 5000,
    buyValue: 10000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: '12 days',
    yield: '1 Bud',
    description: 'Up to 5 points can be added to 1 Skill. But you have to subtract 5 points from other skills.',
  },
  {
    name: 'Miniscule ration',
    damage: 'n/a',
    durability: 1,
    useCost: 0,
    sellValue: 500,
    buyValue: 1000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'Feeds 1 person for 1 day',
  },
  {
    name: 'Minor ration',
    damage: 'n/a',
    durability: 1,
    useCost: 0,
    sellValue: 1000,
    buyValue: 2000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'same as above but heals for 10 health and 20 bar',
  },
  {
    name: 'Major ration',
    damage: 'n/a',
    durability: 1,
    useCost: 0,
    sellValue: 2500,
    buyValue: 5000,
    ammo: 'n/a',
    range: 'n/a',
    weight: 'n/a',
    growthTime: 'n/a',
    yield: 'n/a',
    description: 'fed for a day and 50% health and 50% bar',
  },
];
