// equipmentData.js

export const equipmentList = [
  { name: "Sword", damage: "Melee + 1d6" },
  { name: "Pistol", damage: "2d6", range: "30ft - 60ft", durability: 8 },
  { name: "Rifle", damage: "2d8", range: "30ft - 120ft", durability: 6 },
  { name: "Hammer", damage: "Melee + 1d8" },
  { name: "Axe", damage: "Melee + 1d8" },
  { name: "Spear", damage: "Melee + 1d4", range: "Melee + 5ft" },
  { name: "Trident", damage: "Melee + 1d4", range: "Melee + 5ft" },
  { name: "Knife", damage: "Melee + 1d4" },
  { name: "Chains", damage: "Melee + 1d6", range: "Melee + 10ft" },
  { name: "Shigure", damage: "Melee + 1d8" },
  { name: "Knuckles", damage: "Melee + 1d4" },
  { name: "Scythe", damage: "Melee + 1d6", range: "Melee + 5ft" },
  { name: "Crossbow", damage: "2d4", range: "30ft - 60ft" },
  { name: "Long Neck Rifle", damage: "2d8", range: "30ft - 240ft", durability: 6 },
  { name: "Pistol+MagAttach", damage: "2d6", range: "30ft - 60ft", durability: 10 },

  { name: "Hand Grenade", damage: "3d4", range: "60ft" },
  { name: "Flare", range: "60ft" },
  { name: "Lighter", range: "Melee" },
  { name: "BlastPouch", damage: "2d8", range: "Melee" },
  { name: "Disposable CL", damage: "3d10", range: "30ft - 60ft" },
  { name: "CannonBall", damage: "3d8", range: "60ft - 120ft" },
  { name: "Flame Dial", damage: "2d6", range: "30ft" },
  { name: "Explosive Barrel", damage: "4d10", range: "30ft" },

  { name: "Medical Tools" },
  { name: "Fishing Rod" },
  { name: "Ball Dial" },
  { name: "Breath Dial" },
  { name: "Flash Dial" },
  { name: "Impact Dial" },
  { name: "Lamp Dial" },
  { name: "Reject Dial" },
  { name: "Water Dial" },
  { name: "Ship Repairs" },
  { name: "Medic Kit" },
  { name: "Fluid Pouch" },
  { name: "Iron Dial" },
  { name: "Iron FR" },

  { name: "Other", custom: true }
];